# Generated by Django 4.0.6 on 2022-07-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='title',
            new_name='name',
        ),
    ]
